categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
  - title: "🧰 Maintenance"
    labels: 
      - "maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## What’s Changed
  $CHANGES
