name: Documentation - Deploy to GitHub Pages
on:
  push:
    branches:
      - master
    # Only run action if changes have been made
    # to the documentation or components packages
    paths:
      - "documentation/**"
jobs:
  build:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'      
      - run: yarn install --immutable
      - name: Lint
        run: yarn lint:docs