name: Github Release Labeller
on:
  pull_request_target:
    types: [ opened, edited ]
  push:
    branches:
      - feat/pr-labeller
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
      