name: Github Release Labeller
on:
  # pull_request_target:
  pull_request:
    types: [ opened, edited ]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
      