# Generate a set of screenshots from the test-visual package and upload as an artifact
name: Generate Screenshots
on:
  push:
    branches:
      - master
      - feat/e2e-visual
jobs:
  screenshots_generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - run: yarn install
      - name: Start server and generate screenshots
        run: |
          npx concurrently --kill-others \
          "yarn start" \
          "npx wait-on http-get://localhost:4200 && yarn workspace test-visual start generate"
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: output/screenshots-generated.zip
