# Basic test to ensure PRs pass build. Default runner except when preview deployment already generated
name: Test Lint
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      should-lint: true
      skip-upload: true
