name: Deployment Preview
on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - master
concurrency:
  group: test-preview-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:  
    if: contains(github.event.pull_request.labels.*.name, 'Test - preview')
    uses: ./.github/workflows/web-build.yml
    secrets: inherit
    with:
      build-flags: --configuration "production,preview"
      deployment-env: debug

  deploy_preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: www
      - name: Extract Build folder
        run: |
          mkdir www
          tar -xf artifact.tar --directory www
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLH_TEENS_APP1 }}"
          projectId: plh-teens-app1
          target: "${{needs.build.outputs.DEPLOYMENT_NAME}}"
          expires: 14d
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
