# Generate a set of screenshots for the current branch and compare against previously generated on master
name: Test-Visual Compare Screenshots
on:
  pull_request:
    branches:
      - master
jobs:
  test_visual_compare:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./.yarn/cache
          # If cachebusting required (e.g. breaking yarn changes on update) change `v1` to another number
          key: ${{ runner.os }}-node-modules-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-

      # Download artifact populated from latest `test-visual-generate` workflow run on master branch
      # - name: Download artifact
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     github_token: ${{secrets.GITHUB_TOKEN}}
      #     workflow: test-visual-generate.yml
      #     workflow_conclusion: success
      #     branch: master # TODO replace with master
      #     name: screenshots-artifact
      #     path: extract_here
      # - name: Test
      #   run: cat artifact/sha | grep $GITHUB_SHA

      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - run: yarn install
      - name: Start server and generate screenshots
        # Will always throw error even if successful at end as yarn start script terminated abruptly by\
        # concurrently kill after test-visual complete
        continue-on-error: true
        run: |
          npx concurrently --kill-others \
          "yarn start" \
          "npx wait-on http-get://localhost:4200 && yarn workspace test-visual start compare"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-visual-diffs-artifact # NOTE - must match SCREENSHOT_ARTIFACT_NAME in code
          path: packages/test-visual/output/diffs
          retention-days: 90
          if-no-files-found: error
      - name: "Post to PR"
        uses: EliLillyCo/github-actions-post-to-pr@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          post_to_pr_definition: |
            [
              {
                "message_file": "packages/test-visual/output/summary.txt",
                "title": "test-visual-diffs-artifact",
                "artifact_name": "defaults to title"
              }
            ]
