# Deploy preview url for labelled PRs
# Specifies deployment target based on pr target branch
# Master -> plh_global
# Deployment/{deployment_name} -> {deployment_name}
name: Deployment Preview
on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - deployment/*
      - master
jobs:
 

  build:
    needs: prepare_build_inputs
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build-flags: --configuration "production,preview"

  deploy_preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: www
      - name: Extract Build folder
        run: |
          mkdir www
          tar -xf artifact.tar --directory www
      # - uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: "${{ secrets.GITHUB_TOKEN }}"
      #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLH_TEENS_APP1 }}"
      #     projectId: plh-teens-app1
      #     target: "${{env.DEPLOYMENT_NAME}}"
      #     expires: 14d
      #   env:
      #     FIREBASE_CLI_PREVIEWS: hostingchannels
