# Basic test to ensure PRs pass build. Default runner except when preview deployment already generated
name: Test Build
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    uses: ./.github/workflows/web-build.yml
    secrets: inherit
    environment: debug
    with:
      include-tests: true
      skip-upload: true
      # When testing build binary assets not required
      lfs: false 
      # Load deployment configuration from named environment above (e.g. debug)
      deployment: ${{vars.DEPLOYMENT_NAME}}
      deployment-repo: ${{vars.DEPLOYMENT_REPO}}
      deployment-private-key: ${{secrets.DEPLOYMENT_PRIVATE_KEY}}
