# Manually trigger an android build from Github Actions

name: Trigger Android Debug Build
on:
  workflow_dispatch:
    inputs:
      build_branch:
        required: true
        description: "Specify branch for build"
        default: "master"
  push:
    branches:
      - "cc/flow-updates"
jobs:
  log_build_inputs:
    runs-on: ubuntu-latest
    name: "${{github.event.inputs.build_branch}}"
    steps:
      - run: echo "Build branch ${{github.event.inputs.build_branch}}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          ref: "${{github.event.inputs.build_branch}}"
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Populate firebaseConfig.ts
        env:
          FIREBASE_CONFIG_TS: ${{ secrets.FIREBASE_CONFIG_TS }}
        run: echo $FIREBASE_CONFIG_TS > src/environments/firebaseConfig.ts
      - name: Populate google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: npx cap sync
        run: npx cap sync
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Assemble Android APK's
        working-directory: android
        run: ./gradlew assemble
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          path: android\app\build\outputs\apk\debug\app-debug.apk
